name: tvbox_flutter
description: TVBox cross-platform Flutter rewrite.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  go_router: ^17.1.0
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
